[workspace]
members = [
    "node/bench",
    "node/cli",
    "node/executor",
    "node/inspect",
    "node/rpc",
    "node/testing",
    "runtime",
    "primitives"
]
exclude = [
    'examples/flipper'
]

[profile.release]
panic = "unwind"
