[workspace]
members = [
    "node/*",
    "runtime",
    "primitives",
    "modules/*",
	"modules/evm-utility/macro",
	"pallets/*",
	"pallets/evm/precompile/*",
]
exclude = [
    'examples/flipper'
]

[profile.release]
panic = "unwind"
