[package]
name = "module-evm-bridge"
version = "2.8.0"
authors = []
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1", default-features = false, features = ["derive"] }

[features]
default = ["std"]
std = [
	"codec/std",
]
